### ISSUE TITLE
buddyWentOnline error

### ISSUE THREAD

**Issue by Matak99** [processone/demo-xmpp-ios#4]
Hey,

I'm getting an error when the "func xmppStream(sender: XMPPStream!, didReceivePresence presence: XMPPPresence!)" method is calling "delegate.buddyWentOnline("(presenceFromUser)@..)" 

What am I doing wrong?

**Comment by baoluo** [comment]
Hello @Matak99 Without any code I can't help you, however you can create a question on SO and I'll be glad to help. (this is not a real issue, I'm closing it)
