### ISSUE TITLE
Group Chat

### ISSUE THREAD

**Issue by prvaghela** [processone/demo-xmpp-ios#6]
How can we create group and start chats between created users ?

**Comment by aadilimperoit** [comment]
I am also looking forward to this

**Comment by baoluo** [comment]
Hello @V2PVaghela @aadilimperoit , You can, but there I didn't had the time to create helper classes, so you'll have to use the standard XMPP group chat, there is some documentation on SO.

If you want, you can create the feature and I'll merge it !

I will close this as it's not a defect
