### ISSUE TITLE
compile errors. Xcode 8 Swift 3.0

### ISSUE THREAD

**Issue by usman-whizpool** [processone/demo-xmpp-ios#7]
I followed steps till pod install and open project. It has two compile errors
1. Redefined of module 'dnnsd'
2: compile error on import XMPPFramework

see attachement
![screen shot 2016-09-22 at 4 33 52 pm](https://cloud.githubusercontent.com/assets/5094671/18746747/a86991b6-80e2-11e6-9c7d-a30994ca8f10.png)

**Comment by usman-whizpool** [comment]
Resolved issue 2 by adding "use_frameworks!" to pod file at top

**Comment by usman-whizpool** [comment]
Issue 1 resolved by commenting following code from file "module.modulemap" in KissXML folder of XMPPFramework
/*
module dnssd [system] {
    header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/dns_sd.h"
    export *
}
*/

**Comment by baoluo** [comment]
Ok, so I'll need to send another PR to the XMPPFramework Pod, thank you for sharing

**Comment by Hitaishininfotech** [comment]
I have same issue in Xcode8 and swift2.2
![screen shot 2016-11-03 at 6 58 24 pm](https://cloud.githubusercontent.com/assets/11923868/19967766/b895ed7e-a1f7-11e6-9dd1-2544cd947ac3.png)
